stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/raw/predict-volcanic-eruptions_dataset
    - src/prepare.py
    params:
    - prepare.random_state
    - prepare.test_size
    - prepare.train_size
    outs:
    - data/processed
  train:
    cmd: python src/train.py
    deps:
    - data/processed/processed_training_set.csv
    - data/processed/y_train.csv
    - src/train.py
    params:
    - train
    outs:
    - models
