{
 "title": "Grafana Dashboard",
 "description": "Dashboard for Vulcanic-eruption-prediction project",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "STATUS",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "up{job=\"vulcanic-eruption-prediction\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total number of HTTP requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fastapi_model_http_requests_total{})"
    }
   ]
  },
  {
   "title": "Type of HTTP requests",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (fastapi_model_http_requests_total{}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP requests rate in the last 1m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(fastapi_model_http_requests_total{}[$__interval]))",
     "legendFormat": "HTTP requests"
    }
   ]
  },
  {
   "title": "Current in-progress requests",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(fastapi_inprogress)" }
   ]
  },
  {
   "title": "Request rate in the last minute",
   "type": "gauge",
   "description": "Per-second rate for all time series with the `http_requests_total` metric name, as measured over the last minute",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastapi_model_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Model Type",
   "type": "piechart",
   "description": "Portion of prediction requests directed to each model type.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_model_model_output_count",
     "legendFormat": "{{model_type}}"
    }
   ]
  },
  {
   "title": "Endpoint requests in the last 1m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(fastapi_model_http_requests_total[1m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "Prediction output values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "LGBMRegressor",
   "type": "bargauge",
   "description": "Occurrence of prediction output values for the LGBMRegressor model",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_model_model_output_bucket{model_type=\"LGBMRegressor\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "XGBRegressor",
   "type": "bargauge",
   "description": "Occurrence of prediction output values for the XGBRegressor model",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_model_model_output_bucket{model_type=\"XGBRegressor\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Neural Network",
   "type": "bargauge",
   "description": "Occurrence of prediction output values for the Neural Network model",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_model_model_output_bucket{model_type=\"Neural_Network\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}