name: Deployment
on: 
  push:
    branches:
      - main

  workflow_dispatch:
  
jobs:                    
  deploy_container:
    name: Deploy container
    runs-on: windows-latest     #Actions are JavaScript files or Docker containers. If is a Docker container you must run the job in a Linux virtual environment.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          pip install dvc[gdrive]
      - name: DVC pull
        env: 
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
             dvc pull data/processed/processed_validation_set.csv
             dvc pull models/LGBMRegressor_model.pkl
             dvc pull models/Neural_Network.h5
             dvc pull models/Neural_Network_model.pkl
             dvc pull models/XGBRegressor_model.pkl

      #if: "contains(github.event.head_commit.message, 'make deployment')"
      - name: 'google cloud platform auth'
        uses: 'google-github-actions/auth@v0'
        with:
         credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'
     
      # Build and push image to Google Container Registry
      - name: Set up gcp
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: vulcanic-eruption-prediction

      - name: Building   #Cloud Build will run a remote "docker build -t $TAG 
        run: gcloud builds submit --tag gcr.io/vulcanic-eruption-prediction/backend

      # Setup gcloud CLI
      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: backend
          image: gcr.io/vulcanic-eruption-prediction/backend
          region: europe-west1
          project_id: vulcanic-eruption-prediction
