# This is a basic workflow to help you get started with Actions
name: example

on: [push]
  #pull_request
  # branches:
  #   - master

jobs:
  code-quality-assurance:
    name: Code quality assurance
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set uo Pytohn 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint src/ app/                    

  data-quality-assurance:
    name: Data quality assurance
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Validating data with Great Expectations
        run: python src/data_validation.py        
  
  model-training:
    name: Model training
    needs: [code-quality-assurance, data-quality-assurance]
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pytohn -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Training the model-training
        run: python src/train.py
      - name: Uploading LGBMRegressor model as a Github Actions artifact
        uses: actions/upload-artifact@v2.3.1
        with: 
          name: LGBMRegressor model
          path: models/LGBMRegressor_model.pkl
      - name: Uploading XGBRegressor model as a Github Actions artifact
        uses: actions/upload-artifact@v2.3.1
        with: 
          name: XGBRegressor model
          path: models/XGBRegressor_model.pkl
      - name: Uploading Neural Network model as a Github Actions artifact
        uses: actions/upload-artifact@v2.3.1
        with: 
          name: Neural Network model
          path: models/Neural Network_model.pkl
