name: Test

# Controls when the workflow will run
on:
  
  pull_request:
    branches:
      - main

  workflow_dispatch:
  
jobs:                    
  test:
    name: Test with pytest
    runs-on: windows-latest     #Actions are JavaScript files or Docker containers. If is a Docker container you must run the job in a Linux virtual environment.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          pip install dvc[gdrive]
      - name: DVC pull
        env: 
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
             dvc pull data/processed
             dvc pull models
             dvc pull --glob data/raw/predict-volcanic-eruptions_dataset/train/*1234*
             dvc pull --glob data/raw/predict-volcanic-eruptions_dataset/test/*3456*  
      - name: Test with pytest 
        run: |
          pytest -m training 
          pytest -m evaluation 
          pytest -m api
          