name: Test

# Controls when the workflow will run
on:
  
  pull_request:
    branches:
      - main

  workflow_dispatch:
  
jobs:                  

  data-quality-assurance:
    name: Data quality assurance
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Validating data with Great Expectations
        run: python tests/data_validation/data_validation.py    

  test:
    name: Test with pytest
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Test with pytest
        run: |
          cd tests/app
          pytest -v
          cd tests/src_tests
          pytest -v
